### GET request to example server
GET 127.0.0.1:8000/

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body === "Hello, Rango!", "Response body is not 'Hello, Rango!'")
    });
%}
###

### GET request to example server
GET 127.0.0.1:8000/

###